rename files to avoid : in filenames, which is not valid on Windows (#1248)
These files were introduced in commit aca28cdfa7bba0683a85d9f075209b17c522997e

Renaming them fixes https://github.com/openwallet-foundation/multipaz/issues/1179

Signed-off-by: Tobias Thierer <github@tobias-thierer.de>

Tested on Windows:
Before this commit:
~~~
>git clone https://github.com/openwallet-foundation/multipaz.git
Cloning into 'multipaz'...
remote: Enumerating objects: 42228, done.
remote: Counting objects: 100% (3554/3554), done.
remote: Compressing objects: 100% (1208/1208), done.
remote: Total 42228 (delta 2720), reused 2347 (delta 2292), pack-reused 38674 (from 2)
Receiving objects: 100% (42228/42228), 51.57 MiB | 16.83 MiB/s, done.
Resolving deltas: 100% (18112/18112), done.
error: invalid path 'multipaz-openid4vci-server/src/main/resources/resources/trust/client_attestation/urn:uuid:60f8c117-b692-4de8-8f7f-636ff852baa6.pem'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
~~~

After this commit:

~~~
>git clone multipaz multipaz_copy
Cloning into 'multipaz_copy'...
done.
~~~